# Generated by Django 4.2.7 on 2025-06-23 03:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="userfavorite",
            name="favorite_type_constraint",
        ),
        migrations.AddConstraint(
            model_name="userfavorite",
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(
                        ("favorite_type", "restaurant"),
                        ("product__isnull", True),
                        ("restaurant__isnull", False),
                    ),
                    models.Q(
                        ("favorite_type", "product"),
                        ("product__isnull", False),
                        ("restaurant__isnull", True),
                    ),
                    _connector="OR",
                ),
                name="favorite_type_constraint",
            ),
        ),
    ]
