# Generated by Django 4.2.7 on 2025-07-03 10:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="language",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name="language",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name="translation",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name="translation",
            name="group",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="translation",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
