# Generated by Django 4.2.7 on 2025-07-15 04:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0002_alter_language_created_at_alter_language_updated_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="appsettings",
            name="base_delivery_fee",
            field=models.DecimalField(
                decimal_places=2,
                default=20.0,
                help_text="Base delivery fee in THB",
                max_digits=10,
            ),
        ),
        migrations.AddField(
            model_name="appsettings",
            name="delivery_time_slots",
            field=models.CharField(
                default="09:00-21:00",
                help_text="Delivery time slots (e.g., 09:00-21:00)",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="appsettings",
            name="enable_scheduled_delivery",
            field=models.BooleanField(
                default=True, help_text="Enable scheduled delivery option"
            ),
        ),
        migrations.AddField(
            model_name="appsettings",
            name="free_delivery_minimum",
            field=models.DecimalField(
                decimal_places=2,
                default=200.0,
                help_text="Minimum order amount for free delivery",
                max_digits=10,
            ),
        ),
        migrations.AddField(
            model_name="appsettings",
            name="max_delivery_distance",
            field=models.DecimalField(
                decimal_places=2,
                default=10.0,
                help_text="Maximum delivery distance in km",
                max_digits=5,
            ),
        ),
        migrations.AddField(
            model_name="appsettings",
            name="multi_restaurant_additional_fee",
            field=models.DecimalField(
                decimal_places=2,
                default=1.0,
                help_text="Additional fee per additional restaurant",
                max_digits=5,
            ),
        ),
        migrations.AddField(
            model_name="appsettings",
            name="multi_restaurant_base_fee",
            field=models.DecimalField(
                decimal_places=2,
                default=2.0,
                help_text="Base fee for multi-restaurant orders",
                max_digits=5,
            ),
        ),
        migrations.AddField(
            model_name="appsettings",
            name="per_km_fee",
            field=models.DecimalField(
                decimal_places=2,
                default=5.0,
                help_text="Additional fee per kilometer",
                max_digits=5,
            ),
        ),
        migrations.AddField(
            model_name="appsettings",
            name="rush_hour_multiplier",
            field=models.DecimalField(
                decimal_places=2,
                default=1.5,
                help_text="Delivery fee multiplier during rush hours",
                max_digits=3,
            ),
        ),
        migrations.AddField(
            model_name="appsettings",
            name="weekend_multiplier",
            field=models.DecimalField(
                decimal_places=2,
                default=1.2,
                help_text="Delivery fee multiplier on weekends",
                max_digits=3,
            ),
        ),
    ]
