# Generated by Django 4.2.7 on 2025-06-26 02:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0002_fix_favorite_constraint"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="is_special_only",
            field=models.BooleanField(
                default=False, help_text="เฉพาะร้านพิเศษเท่านั้นที่ใช้หมวดหมู่นี้ได้"
            ),
        ),
    ]
