# Generated by Django 4.2.7 on 2025-06-26 02:34

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0003_add_is_special_only_to_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="image",
            field=models.ImageField(
                blank=True,
                help_text="อัปโหลดรูปภาพสินค้า",
                null=True,
                upload_to=api.models.product_image_upload_path,
            ),
        ),
    ]
