# Generated by Django 4.2.7 on 2025-07-15 06:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0003_appsettings_base_delivery_fee_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="appsettings",
            name="multi_restaurant_additional_fee",
            field=models.DecimalField(
                decimal_places=2,
                default=1.0,
                help_text="Additional fee per additional restaurant",
                max_digits=10,
            ),
        ),
        migrations.AlterField(
            model_name="appsettings",
            name="multi_restaurant_base_fee",
            field=models.DecimalField(
                decimal_places=2,
                default=2.0,
                help_text="Base fee for multi-restaurant orders",
                max_digits=10,
            ),
        ),
    ]
