# Generated by Django 4.2.7 on 2025-07-15 07:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("api", "0004_alter_appsettings_multi_restaurant_additional_fee_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="GuestOrder",
            fields=[
                ("guest_order_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "temporary_id",
                    models.CharField(
                        help_text="Temporary ID for guest order tracking",
                        max_length=50,
                        unique=True,
                    ),
                ),
                ("order_date", models.DateTimeField(auto_now_add=True)),
                ("total_amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("delivery_address", models.CharField(max_length=255)),
                (
                    "delivery_latitude",
                    models.DecimalField(
                        blank=True, decimal_places=8, max_digits=10, null=True
                    ),
                ),
                (
                    "delivery_longitude",
                    models.DecimalField(
                        blank=True, decimal_places=8, max_digits=11, null=True
                    ),
                ),
                (
                    "current_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("paid", "Paid"),
                            ("preparing", "Preparing"),
                            ("ready_for_pickup", "Ready for Pickup"),
                            ("delivering", "Delivering"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "delivery_fee",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                (
                    "estimated_delivery_time",
                    models.DateTimeField(blank=True, null=True),
                ),
                ("customer_name", models.CharField(max_length=100)),
                ("customer_phone", models.CharField(max_length=20)),
                (
                    "customer_email",
                    models.EmailField(blank=True, max_length=254, null=True),
                ),
                ("special_instructions", models.TextField(blank=True, null=True)),
                (
                    "payment_method",
                    models.CharField(default="bank_transfer", max_length=20),
                ),
                ("payment_status", models.CharField(default="pending", max_length=20)),
                (
                    "proof_of_payment",
                    models.ImageField(
                        blank=True, null=True, upload_to="payments/guest_proofs/"
                    ),
                ),
                (
                    "expires_at",
                    models.DateTimeField(help_text="Order expires after 30 days"),
                ),
                (
                    "restaurant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="guest_orders",
                        to="api.restaurant",
                    ),
                ),
            ],
            options={
                "db_table": "guest_orders",
            },
        ),
        migrations.CreateModel(
            name="GuestOrderDetail",
            fields=[
                (
                    "guest_order_detail_id",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("quantity", models.IntegerField()),
                (
                    "price_at_order",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("subtotal", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "guest_order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="order_details",
                        to="api.guestorder",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.product"
                    ),
                ),
            ],
            options={
                "db_table": "guest_order_details",
            },
        ),
        migrations.CreateModel(
            name="GuestDeliveryStatusLog",
            fields=[
                ("log_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("paid", "Paid"),
                            ("preparing", "Preparing"),
                            ("ready_for_pickup", "Ready for Pickup"),
                            ("delivering", "Delivering"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        max_length=20,
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("note", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "guest_order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="status_logs",
                        to="api.guestorder",
                    ),
                ),
                (
                    "updated_by_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "guest_delivery_status_log",
            },
        ),
        migrations.AddIndex(
            model_name="guestorder",
            index=models.Index(
                fields=["temporary_id"], name="guest_order_tempora_653aa9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="guestorder",
            index=models.Index(
                fields=["restaurant", "-order_date"],
                name="guest_order_restaur_424c3c_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="guestorder",
            index=models.Index(
                fields=["current_status"], name="guest_order_current_147de2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="guestorder",
            index=models.Index(
                fields=["expires_at"], name="guest_order_expires_94bb57_idx"
            ),
        ),
    ]
