# Generated by Django 4.2.7 on 2025-07-16 07:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0005_guestorder_guestorderdetail_guestdeliverystatuslog_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="appsettings",
            name="base_delivery_fee",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Base delivery fee in THB",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="appsettings",
            name="free_delivery_minimum",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Minimum order amount for free delivery",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="appsettings",
            name="max_delivery_distance",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Maximum delivery distance in km",
                max_digits=5,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="appsettings",
            name="multi_restaurant_additional_fee",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Additional fee per additional restaurant",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="appsettings",
            name="multi_restaurant_base_fee",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Base fee for multi-restaurant orders",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="appsettings",
            name="per_km_fee",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Additional fee per kilometer",
                max_digits=5,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="guestorder",
            name="delivery_fee",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="delivery_fee",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
    ]
