# Generated by Django 4.2.7 on 2025-07-16 07:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0006_alter_appsettings_base_delivery_fee_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="guestorder",
            name="delivery_fees_by_restaurant",
            field=models.JSONField(
                blank=True,
                help_text="ค่าจัดส่งแยกตามร้าน (restaurant_id: fee)",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="guestorder",
            name="order_details_by_restaurant",
            field=models.JSONField(
                blank=True,
                help_text="รายละเอียดสินค้าแยกตามร้าน (restaurant_id: [...])",
                null=True,
            ),
        ),
    ]
