# Generated by Django 4.2.7 on 2025-06-26 09:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("api", "0006_add_restaurant_image_url"),
    ]

    operations = [
        migrations.CreateModel(
            name="AppSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("app_name", models.CharField(default="Food Delivery", max_length=100)),
                ("app_description", models.TextField(default="ระบบสั่งอาหารออนไลน์")),
                (
                    "app_logo",
                    models.ImageField(blank=True, null=True, upload_to="app/logos/"),
                ),
                (
                    "app_banner",
                    models.ImageField(blank=True, null=True, upload_to="app/banners/"),
                ),
                (
                    "contact_email",
                    models.EmailField(
                        default="support@fooddelivery.com", max_length=254
                    ),
                ),
                (
                    "contact_phone",
                    models.CharField(default="02-xxx-xxxx", max_length=20),
                ),
                (
                    "contact_address",
                    models.TextField(default="123 ถนนสุขุมวิท กรุงเทพฯ 10110"),
                ),
                (
                    "hero_title",
                    models.CharField(
                        default="สั่งอาหารง่ายๆ ส่งถึงบ้านคุณ", max_length=200
                    ),
                ),
                (
                    "hero_subtitle",
                    models.CharField(
                        default="เลือกจากร้านอาหารชั้นนำ ส่งเร็ว อร่อย ปลอดภัย",
                        max_length=300,
                    ),
                ),
                (
                    "feature_1_title",
                    models.CharField(default="ส่งเร็ว", max_length=100),
                ),
                (
                    "feature_1_description",
                    models.CharField(
                        default="ส่งอาหารถึงมือคุณภายใน 30-45 นาที", max_length=200
                    ),
                ),
                ("feature_1_icon", models.CharField(default="🚚", max_length=10)),
                (
                    "feature_2_title",
                    models.CharField(default="คุณภาพดี", max_length=100),
                ),
                (
                    "feature_2_description",
                    models.CharField(
                        default="ร้านอาหารคุณภาพ ผ่านการคัดเลือก", max_length=200
                    ),
                ),
                ("feature_2_icon", models.CharField(default="🍽️", max_length=10)),
                (
                    "feature_3_title",
                    models.CharField(default="จ่ายง่าย", max_length=100),
                ),
                (
                    "feature_3_description",
                    models.CharField(
                        default="รองรับการชำระเงินหลายช่องทาง", max_length=200
                    ),
                ),
                ("feature_3_icon", models.CharField(default="💳", max_length=10)),
                ("facebook_url", models.URLField(blank=True, null=True)),
                ("instagram_url", models.URLField(blank=True, null=True)),
                ("twitter_url", models.URLField(blank=True, null=True)),
                (
                    "meta_keywords",
                    models.TextField(
                        blank=True, help_text="คำค้นหาหลัก (คั่นด้วยจุลภาค)"
                    ),
                ),
                (
                    "meta_description",
                    models.TextField(blank=True, help_text="คำอธิบายสำหรับ SEO"),
                ),
                ("maintenance_mode", models.BooleanField(default=False)),
                (
                    "maintenance_message",
                    models.TextField(
                        default="ระบบอยู่ระหว่างการปรับปรุง กรุณาลองใหม่อีกครั้ง"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "App Settings",
                "verbose_name_plural": "App Settings",
            },
        ),
    ]
