# Generated by Django 4.2.7 on 2025-07-16 07:44

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0007_guestorder_delivery_fees_by_restaurant_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="guestorder",
            name="delivery_fees_by_restaurant",
        ),
        migrations.RemoveField(
            model_name="guestorder",
            name="order_details_by_restaurant",
        ),
    ]
