# Generated by Django 4.2.7 on 2025-06-26 11:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0007_appsettings"),
    ]

    operations = [
        migrations.AlterField(
            model_name="appsettings",
            name="app_description",
            field=models.TextField(blank=True, default="ระบบสั่งอาหารออนไลน์"),
        ),
        migrations.AlterField(
            model_name="appsettings",
            name="contact_address",
            field=models.TextField(blank=True, default="กรุงเทพฯ ประเทศไทย"),
        ),
        migrations.AlterField(
            model_name="appsettings",
            name="contact_email",
            field=models.EmailField(
                blank=True, default="support@fooddelivery.com", max_length=254
            ),
        ),
        migrations.AlterField(
            model_name="appsettings",
            name="contact_phone",
            field=models.CharField(blank=True, default="02-xxx-xxxx", max_length=20),
        ),
        migrations.AlterField(
            model_name="appsettings",
            name="hero_title",
            field=models.CharField(
                blank=True, default="สั่งอาหารจากร้านโปรด", max_length=200
            ),
        ),
    ]
