# Generated by Django 4.2.7 on 2025-06-27 03:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0008_alter_appsettings_app_description_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="appsettings",
            name="currency",
            field=models.CharField(
                default="THB", help_text="สกุลเงินที่ใช้", max_length=3
            ),
        ),
        migrations.AddField(
            model_name="appsettings",
            name="timezone",
            field=models.CharField(
                default="Asia/Bangkok", help_text="เขตเวลาของระบบ", max_length=50
            ),
        ),
    ]
