# Generated by Django 4.2.7 on 2025-07-16 08:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0008_remove_guestorder_delivery_fees_by_restaurant_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="guestorder",
            name="restaurants",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="For multi-restaurant orders: [{'restaurant_id': 1, 'restaurant_name': 'Restaurant 1', 'delivery_fee': 50.00}, ...]",
            ),
        ),
        migrations.AddField(
            model_name="guestorderdetail",
            name="restaurant",
            field=models.ForeignKey(
                blank=True,
                help_text="Restaurant for this order detail",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="api.restaurant",
            ),
        ),
        migrations.AlterField(
            model_name="guestorder",
            name="delivery_fee",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Total delivery fee for all restaurants",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="guestorder",
            name="restaurant",
            field=models.ForeignKey(
                blank=True,
                help_text="For single restaurant orders",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="guest_orders",
                to="api.restaurant",
            ),
        ),
        migrations.AddIndex(
            model_name="guestorderdetail",
            index=models.Index(
                fields=["guest_order", "restaurant"],
                name="guest_order_guest_o_3168bc_idx",
            ),
        ),
    ]
