# Generated by Django 4.2.7 on 2025-06-27 03:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0009_appsettings_currency_appsettings_timezone"),
    ]

    operations = [
        migrations.AddField(
            model_name="appsettings",
            name="bank_account_name",
            field=models.CharField(blank=True, help_text="ชื่อบัญชี", max_length=100),
        ),
        migrations.AddField(
            model_name="appsettings",
            name="bank_account_number",
            field=models.CharField(
                blank=True, help_text="เลขบัญชีธนาคาร", max_length=50
            ),
        ),
        migrations.AddField(
            model_name="appsettings",
            name="bank_name",
            field=models.CharField(
                blank=True,
                default="ธนาคารกรุงเทพ",
                help_text="ชื่อธนาคาร",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="appsettings",
            name="qr_code_image",
            field=models.ImageField(
                blank=True,
                help_text="รูป QR Code สำหรับการชำระเงิน",
                null=True,
                upload_to="app/payment/",
            ),
        ),
    ]
