# Generated by Django 4.2.7 on 2025-08-28 03:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0009_guestorder_restaurants_guestorderdetail_restaurant_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="related_guest_order",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="api.guestorder",
            ),
        ),
    ]
