# Generated by Django 4.2.7 on 2025-06-27 03:41

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0010_appsettings_bank_account_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="proof_of_payment",
            field=models.ImageField(
                blank=True,
                help_text="หลักฐานการโอนเงิน",
                null=True,
                upload_to=api.models.payment_proof_upload_path,
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="payment_method",
            field=models.CharField(
                choices=[
                    ("qr_payment", "QR Payment"),
                    ("bank_transfer", "Bank Transfer"),
                ],
                max_length=20,
            ),
        ),
    ]
