# Generated by Django 4.2.7 on 2025-08-28 04:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0010_notification_related_guest_order"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="type",
            field=models.CharField(
                choices=[
                    ("order_update", "Order Update"),
                    ("guest_order_update", "Guest Order Update"),
                    ("payment_confirm", "Payment Confirmation"),
                    ("review_reminder", "Review Reminder"),
                    ("promotion", "Promotion"),
                    ("system", "System"),
                    ("new_restaurant_registration", "New Restaurant Registration"),
                    ("upgrade", "Account Upgrade"),
                    ("downgrade", "Account Downgrade"),
                ],
                max_length=30,
            ),
        ),
    ]
