# Generated by Django 4.2.7 on 2025-06-27 04:48

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0011_payment_proof_of_payment_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="description",
            field=models.TextField(blank=True, help_text="คำอธิบายหมวดหมู่", null=True),
        ),
        migrations.AddField(
            model_name="category",
            name="image",
            field=models.ImageField(
                blank=True,
                help_text="รูปภาพหมวดหมู่",
                null=True,
                upload_to=api.models.category_image_upload_path,
            ),
        ),
    ]
