# Generated by Django 4.2.7 on 2025-10-03 03:52

from django.db import migrations, models


def update_sort_order(apps, schema_editor):
    """อัปเดต sort_order ให้ไม่ซ้ำกัน"""
    Category = apps.get_model('api', 'Category')
    for idx, category in enumerate(Category.objects.all().order_by('category_id'), start=1):
        category.sort_order = idx
        category.save()


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_notification_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['sort_order', 'category_name'], 'verbose_name_plural': 'Categories'},
        ),
        migrations.AddField(
            model_name='category',
            name='sort_order',
            field=models.PositiveIntegerField(default=0, help_text='Order for sorting categories'),
        ),
        # อัปเดตข้อมูลให้ sort_order ไม่ซ้ำกัน
        migrations.RunPython(update_sort_order, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('order', 'Order'), ('guest_order', 'Guest Order'), ('payment_confirm', 'Payment Confirmation'), ('review_reminder', 'Review Reminder'), ('promotion', 'Promotion'), ('system', 'System'), ('new_restaurant_registration', 'New Restaurant Registration'), ('upgrade', 'Account Upgrade'), ('downgrade', 'Account Downgrade')], max_length=30),
        ),
    ]
