# Generated by Django 4.2.7 on 2025-10-03 04:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0013_alter_category_options_category_sort_order_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="sort_order",
            field=models.PositiveIntegerField(
                default=0, help_text="Order for sorting categories", unique=True
            ),
        ),
    ]
