# Generated by Django 4.2.7 on 2025-10-06 04:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0014_alter_category_sort_order"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductTranslation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("translated_name", models.CharField(max_length=150)),
                ("translated_description", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "language",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="product_translations",
                        to="api.language",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="translations",
                        to="api.product",
                    ),
                ),
            ],
            options={
                "db_table": "product_translations",
                "indexes": [
                    models.Index(
                        fields=["product"], name="product_tra_product_63da9c_idx"
                    ),
                    models.Index(
                        fields=["language"], name="product_tra_languag_5147db_idx"
                    ),
                ],
                "unique_together": {("product", "language")},
            },
        ),
        migrations.CreateModel(
            name="CategoryTranslation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("translated_name", models.CharField(max_length=100)),
                ("translated_description", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="translations",
                        to="api.category",
                    ),
                ),
                (
                    "language",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="category_translations",
                        to="api.language",
                    ),
                ),
            ],
            options={
                "db_table": "category_translations",
                "indexes": [
                    models.Index(
                        fields=["category"], name="category_tr_categor_3a1f7b_idx"
                    ),
                    models.Index(
                        fields=["language"], name="category_tr_languag_615d66_idx"
                    ),
                ],
                "unique_together": {("category", "language")},
            },
        ),
    ]
