# Generated by Django 4.2.7 on 2025-10-07 04:35

import api.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("api", "0015_add_translation_tables"),
    ]

    operations = [
        migrations.CreateModel(
            name="Advertisement",
            fields=[
                (
                    "advertisement_id",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="ชื่อโฆษณา (สำหรับแอดมินเท่านั้น)", max_length=200
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, help_text="คำอธิบายโฆษณา", null=True),
                ),
                (
                    "image",
                    models.ImageField(
                        help_text="รูปภาพโฆษณา (แนะนำ 800x400px)",
                        upload_to=api.models.advertisement_image_upload_path,
                    ),
                ),
                (
                    "image_url",
                    models.URLField(
                        blank=True,
                        help_text="URL รูปภาพ (ถ้าไม่ใช้ upload)",
                        max_length=500,
                        null=True,
                    ),
                ),
                (
                    "link_url",
                    models.URLField(
                        blank=True,
                        help_text="ลิงก์ปลายทาง (เมื่อคลิกโฆษณา)",
                        max_length=500,
                        null=True,
                    ),
                ),
                (
                    "sort_order",
                    models.PositiveIntegerField(
                        default=0, help_text="ลำดับการแสดงผล (เลขน้อยแสดงก่อน)"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, help_text="เปิดใช้งานโฆษณา"),
                ),
                (
                    "start_date",
                    models.DateTimeField(
                        blank=True, help_text="วันเริ่มแสดงโฆษณา", null=True
                    ),
                ),
                (
                    "end_date",
                    models.DateTimeField(
                        blank=True, help_text="วันสิ้นสุดการแสดงโฆษณา", null=True
                    ),
                ),
                (
                    "click_count",
                    models.PositiveIntegerField(
                        default=0, help_text="จำนวนครั้งที่ถูกคลิก"
                    ),
                ),
                (
                    "view_count",
                    models.PositiveIntegerField(
                        default=0, help_text="จำนวนครั้งที่ถูกแสดง"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_advertisements",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "advertisements",
                "ordering": ["sort_order", "-created_at"],
                "indexes": [
                    models.Index(
                        fields=["is_active", "sort_order"],
                        name="advertiseme_is_acti_5993ee_idx",
                    ),
                    models.Index(
                        fields=["start_date", "end_date"],
                        name="advertiseme_start_d_fe9acd_idx",
                    ),
                ],
            },
        ),
    ]
