# Generated by Django 4.2.7 on 2025-10-07 04:42

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0016_advertisement"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="advertisement",
            name="advertiseme_start_d_fe9acd_idx",
        ),
        migrations.RemoveField(
            model_name="advertisement",
            name="click_count",
        ),
        migrations.RemoveField(
            model_name="advertisement",
            name="created_by",
        ),
        migrations.RemoveField(
            model_name="advertisement",
            name="description",
        ),
        migrations.RemoveField(
            model_name="advertisement",
            name="end_date",
        ),
        migrations.RemoveField(
            model_name="advertisement",
            name="image_url",
        ),
        migrations.RemoveField(
            model_name="advertisement",
            name="link_url",
        ),
        migrations.RemoveField(
            model_name="advertisement",
            name="start_date",
        ),
        migrations.RemoveField(
            model_name="advertisement",
            name="title",
        ),
        migrations.RemoveField(
            model_name="advertisement",
            name="view_count",
        ),
    ]
