# Generated by Django 4.2.7 on 2025-11-18 04:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0017_remove_advertisement_advertiseme_start_d_fe9acd_idx_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="restaurant",
            name="latitude",
            field=models.DecimalField(
                blank=True,
                decimal_places=8,
                help_text="Restaurant latitude",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="restaurant",
            name="longitude",
            field=models.DecimalField(
                blank=True,
                decimal_places=8,
                help_text="Restaurant longitude",
                max_digits=11,
                null=True,
            ),
        ),
    ]
