# Generated by Django 4.2.7 on 2025-11-18 07:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0018_restaurant_latitude_restaurant_longitude"),
    ]

    operations = [
        migrations.AlterField(
            model_name="appsettings",
            name="max_delivery_distance",
            field=models.DecimalField(
                blank=True,
                decimal_places=0,
                help_text="Maximum delivery distance in km",
                max_digits=6,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="appsettings",
            name="per_km_fee",
            field=models.DecimalField(
                blank=True,
                decimal_places=0,
                help_text="Additional fee per kilometer",
                max_digits=6,
                null=True,
            ),
        ),
    ]
