# Generated by Django 4.2.7 on 2025-11-18 09:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0019_alter_appsettings_max_delivery_distance_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="guestorder",
            name="delivery_fee",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Total delivery fee for all restaurants",
                max_digits=15,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="guestorder",
            name="total_amount",
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
        migrations.AlterField(
            model_name="guestorderdetail",
            name="price_at_order",
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
        migrations.AlterField(
            model_name="guestorderdetail",
            name="subtotal",
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
        migrations.AlterField(
            model_name="order",
            name="delivery_fee",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=15, null=True
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="total_amount",
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
        migrations.AlterField(
            model_name="orderdetail",
            name="price_at_order",
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
        migrations.AlterField(
            model_name="orderdetail",
            name="subtotal",
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
        migrations.AlterField(
            model_name="payment",
            name="amount_paid",
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
        migrations.AlterField(
            model_name="product",
            name="price",
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
    ]
