# Generated by Django 4.2.7 on 2025-11-18 09:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0020_increase_price_limits"),
    ]

    operations = [
        migrations.AlterField(
            model_name="guestorder",
            name="delivery_latitude",
            field=models.DecimalField(
                blank=True, decimal_places=8, max_digits=15, null=True
            ),
        ),
        migrations.AlterField(
            model_name="guestorder",
            name="delivery_longitude",
            field=models.DecimalField(
                blank=True, decimal_places=8, max_digits=15, null=True
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="delivery_latitude",
            field=models.DecimalField(
                blank=True, decimal_places=8, max_digits=15, null=True
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="delivery_longitude",
            field=models.DecimalField(
                blank=True, decimal_places=8, max_digits=15, null=True
            ),
        ),
        migrations.AlterField(
            model_name="restaurant",
            name="latitude",
            field=models.DecimalField(
                blank=True,
                decimal_places=8,
                help_text="Restaurant latitude",
                max_digits=15,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="restaurant",
            name="longitude",
            field=models.DecimalField(
                blank=True,
                decimal_places=8,
                help_text="Restaurant longitude",
                max_digits=15,
                null=True,
            ),
        ),
    ]
