# Generated by Django 4.2.7 on 2025-11-19 02:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0023_increase_decimal_places"),
    ]

    operations = [
        migrations.AlterField(
            model_name="guestorder",
            name="delivery_address",
            field=models.CharField(
                help_text="ที่อยู่จัดส่งหลักและรายละเอียดเพิ่มเติม", max_length=500
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="delivery_address",
            field=models.CharField(
                help_text="ที่อยู่จัดส่งหลักและรายละเอียดเพิ่มเติม", max_length=500
            ),
        ),
    ]
