# Generated by Django 4.2.7 on 2025-12-19 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_increase_delivery_address_length'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery_address',
            field=models.CharField(help_text='additional delivery address', max_length=500),
        ),
    ]
