# Generated by Django 4.2.7 on 2025-12-22 02:49

import api.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0025_alter_order_delivery_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='DineInCart',
            fields=[
                ('cart_id', models.AutoField(primary_key=True, serialize=False)),
                ('session_id', models.CharField(help_text='Session ID สำหรับแยกแต่ละการสั่ง', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, help_text='ตะกร้ายังใช้งานอยู่หรือไม่')),
                ('customer_name', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'dine_in_carts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DineInOrder',
            fields=[
                ('dine_in_order_id', models.AutoField(primary_key=True, serialize=False)),
                ('session_id', models.CharField(help_text='Session ID ที่สร้างออเดอร์', max_length=100)),
                ('order_date', models.DateTimeField(auto_now_add=True)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('current_status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('preparing', 'Preparing'), ('ready', 'Ready to Serve'), ('served', 'Served'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('payment_status', models.CharField(choices=[('unpaid', 'Unpaid'), ('paid', 'Paid')], default='unpaid', max_length=20)),
                ('customer_name', models.CharField(blank=True, max_length=100, null=True)),
                ('customer_count', models.PositiveIntegerField(default=1, help_text='จำนวนลูกค้าที่โต๊ะ')),
                ('special_instructions', models.TextField(blank=True, null=True)),
                ('payment_method', models.CharField(blank=True, max_length=20, null=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dine_in_orders', to='api.restaurant')),
            ],
            options={
                'db_table': 'dine_in_orders',
                'ordering': ['-order_date'],
            },
        ),
        migrations.CreateModel(
            name='RestaurantTable',
            fields=[
                ('table_id', models.AutoField(primary_key=True, serialize=False)),
                ('table_number', models.CharField(help_text='หมายเลขโต๊ะ (เช่น A1, B2, 101)', max_length=20)),
                ('qr_code_data', models.CharField(help_text='ข้อมูลใน QR Code (unique token)', max_length=255, unique=True)),
                ('qr_code_image', models.ImageField(blank=True, help_text='รูป QR Code', null=True, upload_to='tables/qr_codes/')),
                ('qr_code_image_url', models.CharField(blank=True, help_text='URL ของ QR Code', max_length=500, null=True)),
                ('is_active', models.BooleanField(default=True, help_text='โต๊ะเปิดใช้งานหรือไม่')),
                ('seats', models.PositiveIntegerField(default=4, help_text='จำนวนที่นั่ง')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tables', to='api.restaurant')),
            ],
            options={
                'db_table': 'restaurant_tables',
                'ordering': ['restaurant', 'table_number'],
            },
        ),
        migrations.CreateModel(
            name='DineInStatusLog',
            fields=[
                ('log_id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('preparing', 'Preparing'), ('ready', 'Ready to Serve'), ('served', 'Served'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('note', models.CharField(blank=True, max_length=255, null=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_logs', to='api.dineinorder')),
                ('updated_by_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'dine_in_status_log',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='DineInProduct',
            fields=[
                ('dine_in_product_id', models.AutoField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('price', models.DecimalField(decimal_places=2, help_text='ราคาสำหรับขายในร้าน', max_digits=15)),
                ('image_url', models.CharField(blank=True, max_length=255, null=True)),
                ('image', models.ImageField(blank=True, help_text='รูปสินค้า Dine-in', null=True, upload_to=api.models.dine_in_product_image_upload_path)),
                ('is_available', models.BooleanField(default=True, help_text='พร้อมขายหรือไม่')),
                ('sort_order', models.PositiveIntegerField(default=0, help_text='ลำดับการแสดงในเมนู')),
                ('is_recommended', models.BooleanField(default=False, help_text='เมนูแนะนำ')),
                ('preparation_time', models.PositiveIntegerField(blank=True, help_text='เวลาในการเตรียม (นาที)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dine_in_products', to='api.category')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dine_in_products', to='api.restaurant')),
            ],
            options={
                'db_table': 'dine_in_products',
                'ordering': ['sort_order', 'product_name'],
            },
        ),
        migrations.CreateModel(
            name='DineInOrderDetail',
            fields=[
                ('order_detail_id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.PositiveIntegerField()),
                ('price_at_order', models.DecimalField(decimal_places=2, max_digits=15)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=15)),
                ('special_instructions', models.TextField(blank=True, null=True)),
                ('dine_in_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.dineinproduct')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_details', to='api.dineinorder')),
            ],
            options={
                'db_table': 'dine_in_order_details',
            },
        ),
        migrations.AddField(
            model_name='dineinorder',
            name='table',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='api.restauranttable'),
        ),
        migrations.CreateModel(
            name='DineInCartItem',
            fields=[
                ('cart_item_id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('price_at_add', models.DecimalField(decimal_places=2, help_text='ราคาขณะเพิ่มลงตะกร้า', max_digits=15)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=15)),
                ('special_instructions', models.TextField(blank=True, help_text='คำขอพิเศษสำหรับรายการนี้', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='api.dineincart')),
                ('dine_in_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.dineinproduct')),
            ],
            options={
                'db_table': 'dine_in_cart_items',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='dineincart',
            name='table',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carts', to='api.restauranttable'),
        ),
        migrations.AddIndex(
            model_name='restauranttable',
            index=models.Index(fields=['restaurant', 'is_active'], name='restaurant__restaur_48b3ca_idx'),
        ),
        migrations.AddIndex(
            model_name='restauranttable',
            index=models.Index(fields=['qr_code_data'], name='restaurant__qr_code_ef2403_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='restauranttable',
            unique_together={('restaurant', 'table_number')},
        ),
        migrations.AddIndex(
            model_name='dineinproduct',
            index=models.Index(fields=['restaurant', 'is_available'], name='dine_in_pro_restaur_d7927e_idx'),
        ),
        migrations.AddIndex(
            model_name='dineinproduct',
            index=models.Index(fields=['category'], name='dine_in_pro_categor_70dc05_idx'),
        ),
        migrations.AddIndex(
            model_name='dineinproduct',
            index=models.Index(fields=['sort_order'], name='dine_in_pro_sort_or_866992_idx'),
        ),
        migrations.AddIndex(
            model_name='dineinorder',
            index=models.Index(fields=['restaurant', '-order_date'], name='dine_in_ord_restaur_d895a0_idx'),
        ),
        migrations.AddIndex(
            model_name='dineinorder',
            index=models.Index(fields=['table', '-order_date'], name='dine_in_ord_table_i_d0cef7_idx'),
        ),
        migrations.AddIndex(
            model_name='dineinorder',
            index=models.Index(fields=['current_status'], name='dine_in_ord_current_5aa015_idx'),
        ),
        migrations.AddIndex(
            model_name='dineinorder',
            index=models.Index(fields=['session_id'], name='dine_in_ord_session_ca72db_idx'),
        ),
        migrations.AddIndex(
            model_name='dineincart',
            index=models.Index(fields=['table', 'is_active'], name='dine_in_car_table_i_a044c2_idx'),
        ),
        migrations.AddIndex(
            model_name='dineincart',
            index=models.Index(fields=['session_id'], name='dine_in_car_session_6b73c6_idx'),
        ),
    ]
