# Generated by Django 4.2.7 on 2025-12-22 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_dineincart_dineinorder_restauranttable_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dineinorder',
            name='bill_requested',
            field=models.BooleanField(default=False, help_text='ลูกค้าร้องขอเช็กบิล'),
        ),
        migrations.AddField(
            model_name='dineinorder',
            name='bill_requested_at',
            field=models.DateTimeField(blank=True, help_text='เวลาที่ร้องขอเช็กบิล', null=True),
        ),
    ]
