# Generated by Django 4.2.7 on 2025-12-29 06:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0029_dineinorderdetail_served_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dineinorder',
            name='current_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('served', 'Served'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='dineinorderdetail',
            name='served_by',
            field=models.ForeignKey(blank=True, help_text='พนักงานที่เสิร์ฟ', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='served_order_details', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='dineinstatuslog',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('served', 'Served'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], max_length=20),
        ),
    ]
