# Generated by Django 4.2.7 on 2026-01-22 09:01

import api.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_alter_dineinorder_current_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VenueCategory',
            fields=[
                ('category_id', models.AutoField(primary_key=True, serialize=False)),
                ('category_name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('icon', models.ImageField(blank=True, help_text='Icon for category', null=True, upload_to=api.models.venue_category_icon_upload_path)),
                ('icon_url', models.CharField(blank=True, help_text='Icon URL (alternative to icon)', max_length=255, null=True)),
                ('sort_order', models.PositiveIntegerField(default=0, help_text='Order for sorting categories')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'venue_categories',
                'ordering': ['sort_order', 'category_name'],
                'indexes': [models.Index(fields=['category_name'], name='venue_categ_categor_5b1daa_idx'), models.Index(fields=['sort_order'], name='venue_categ_sort_or_6a6e62_idx'), models.Index(fields=['is_active'], name='venue_categ_is_acti_2024ca_idx')],
            },
        ),
        migrations.CreateModel(
            name='EntertainmentVenue',
            fields=[
                ('venue_id', models.AutoField(primary_key=True, serialize=False)),
                ('venue_name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('address', models.CharField(max_length=500)),
                ('latitude', models.DecimalField(blank=True, decimal_places=12, help_text='Venue latitude', max_digits=20, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=12, help_text='Venue longitude', max_digits=20, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('opening_hours', models.CharField(blank=True, help_text="Opening hours (e.g., '18:00 - 02:00')", max_length=200, null=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('closed', 'Closed')], default='open', max_length=10)),
                ('venue_type', models.CharField(blank=True, help_text='Type of venue (deprecated, use category)', max_length=100, null=True)),
                ('image', models.ImageField(blank=True, help_text='Main venue image', null=True, upload_to='entertainment_venues/')),
                ('image_url', models.CharField(blank=True, help_text='Main venue image URL (alternative to image)', max_length=255, null=True)),
                ('average_rating', models.DecimalField(decimal_places=2, default=0.0, max_digits=3)),
                ('total_reviews', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, help_text='Venue category', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='venues', to='api.venuecategory')),
            ],
            options={
                'db_table': 'entertainment_venues',
            },
        ),
        migrations.CreateModel(
            name='VenueImage',
            fields=[
                ('image_id', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.ImageField(blank=True, help_text='Venue image', null=True, upload_to=api.models.venue_image_upload_path)),
                ('image_url', models.CharField(blank=True, help_text='Venue image URL (alternative to image)', max_length=255, null=True)),
                ('caption', models.CharField(blank=True, help_text='Image caption', max_length=255, null=True)),
                ('sort_order', models.PositiveIntegerField(default=0, help_text='Order for sorting images')),
                ('is_primary', models.BooleanField(default=False, help_text='Is this the primary image?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='api.entertainmentvenue')),
            ],
            options={
                'db_table': 'venue_images',
                'ordering': ['sort_order', 'created_at'],
                'indexes': [models.Index(fields=['venue', 'sort_order'], name='venue_image_venue_i_4732c5_idx'), models.Index(fields=['is_primary'], name='venue_image_is_prim_2d0f23_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='entertainmentvenue',
            index=models.Index(fields=['venue_name'], name='entertainme_venue_n_bb2a77_idx'),
        ),
        migrations.AddIndex(
            model_name='entertainmentvenue',
            index=models.Index(fields=['-average_rating'], name='entertainme_average_d440c2_idx'),
        ),
        migrations.AddIndex(
            model_name='entertainmentvenue',
            index=models.Index(fields=['status'], name='entertainme_status_9cd828_idx'),
        ),
        migrations.AddIndex(
            model_name='entertainmentvenue',
            index=models.Index(fields=['category'], name='entertainme_categor_42a360_idx'),
        ),
        migrations.AddIndex(
            model_name='entertainmentvenue',
            index=models.Index(fields=['latitude', 'longitude'], name='entertainme_latitud_252a4e_idx'),
        ),
    ]
