# Generated by Django 4.2.7 on 2026-01-23 02:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0031_venuecategory_entertainmentvenue_venueimage_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VenueReview',
            fields=[
                ('review_id', models.AutoField(primary_key=True, serialize=False)),
                ('rating', models.IntegerField(help_text='Rating from 1 to 5')),
                ('comment', models.TextField(blank=True, help_text='Review comment', null=True)),
                ('review_date', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='venue_reviews', to=settings.AUTH_USER_MODEL)),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='venue_reviews', to='api.entertainmentvenue')),
            ],
            options={
                'db_table': 'venue_reviews',
                'indexes': [models.Index(fields=['venue', '-review_date'], name='venue_revie_venue_i_914685_idx'), models.Index(fields=['user'], name='venue_revie_user_id_df9493_idx'), models.Index(fields=['rating'], name='venue_revie_rating_4a5092_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='venuereview',
            constraint=models.CheckConstraint(check=models.Q(('rating__gte', 1), ('rating__lte', 5)), name='venue_rating_range'),
        ),
        migrations.AlterUniqueTogether(
            name='venuereview',
            unique_together={('venue', 'user')},
        ),
    ]
