# Generated by Django 4.2.7 on 2026-03-06 12:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0033_allow_restaurant_review_without_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='DineInProductTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('translated_name', models.CharField(max_length=150)),
                ('translated_description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dine_in_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='api.dineinproduct')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dine_in_product_translations', to='api.language')),
            ],
            options={
                'db_table': 'dine_in_product_translations',
                'unique_together': {('dine_in_product', 'language')},
            },
        ),
        migrations.AddIndex(
            model_name='dineinproducttranslation',
            index=models.Index(fields=['dine_in_product'], name='dine_in_pro_dine_in_2f5fee_idx'),
        ),
        migrations.AddIndex(
            model_name='dineinproducttranslation',
            index=models.Index(fields=['language'], name='dine_in_pro_languag_0b7e11_idx'),
        ),
    ]
