# Generated by Django 4.2.7 on 2026-04-23 03:48

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0039_venuetranslation'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='country',
            new_name='countries_is_acti_1974d8_idx',
            old_name='countries_active_sort_idx',
        ),
        migrations.RenameIndex(
            model_name='dineinproducttranslation',
            new_name='dine_in_pro_dine_in_c3701d_idx',
            old_name='dine_in_pro_dine_in_2f5fee_idx',
        ),
        migrations.RenameIndex(
            model_name='dineinproducttranslation',
            new_name='dine_in_pro_languag_4054b3_idx',
            old_name='dine_in_pro_languag_0b7e11_idx',
        ),
        migrations.AlterField(
            model_name='country',
            name='flag',
            field=models.ImageField(blank=True, help_text='รูปธงชาติ (แนะนำสัดส่วนใกล้เคียง 4:3 หรือสี่เหลี่ยมจัตุรัส)', null=True, upload_to=api.models.country_flag_upload_path),
        ),
        migrations.AlterField(
            model_name='venuetranslation',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AddIndex(
            model_name='city',
            index=models.Index(fields=['country'], name='cities_country_75dd0f_idx'),
        ),
    ]
