# Generated by Django 4.2.7 on 2025-07-01 09:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0004_user_google_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(
                error_messages={"unique": "อีเมลนี้ถูกใช้งานแล้ว กรุณาใช้อีเมลอื่น"},
                help_text="Required. Enter a valid email address.",
                max_length=254,
                unique=True,
                verbose_name="email address",
            ),
        ),
    ]
